### ISSUE TITLE
Upstream ob-ipython has added support to async run

### ISSUE THREAD

**Issue by et2010** [jkitchin/scimax#109]
Hi, John

The upstream ob-ipython has just merged a few PRs and now it also supports async execution. What do you think about it? Any plan to rebase your excellent work onto upstream or keep the way it is now? I'm asking because as an enthusiastic user, I would like to see the two working together, seamlessly. And I don't wanna miss any major updates from both sides. What should I do? Am I asking too much? Anyway, thanks for your time and kudos for your great repo!

**Comment by jkitchin** [comment]
I am not sure where this will go. The two approaches are pretty different in spirit. The upstream one uses a header var and does not appear to support queuing (it does some things nicer though). That is arguably more in the style of org-babel. I haven't tested it yet to see how it handles running more than one cell asynchronously, or cells in different buffers.
 
My approach uses a global variable, automatically names the session/kernel on a per-buffer basis and does support queuing. It would be a pretty non-trivial merge. It would be easy to remove the global var and use a default header argument to better align that part, but the rest is not that easy to align. I feel like the whole setup could be simpler if we could avoid the web server that communicates with the kernel, but this is currently needed because there is no 0mq library for emacs to communicate directly. 

For the next few weeks things will be as they are. I will touch base with @gregsexton to see where ob-ipython is heading and what features make sense to put in the project.

**Comment by gregsexton** [comment]
I could probably get queuing to work pretty easily. What problem does it solve for you? I'm not a heavy user of async.

I don't really have a notifications channel for the project, so while I'm here I thought you guys might be interested in a change I landed today. I improved 'cell' rendering. ob-ipython behaves more like the notebook now. No need to specify file paths. images just get rendered if something is produced and results are displayed too. If you have pandoc, same goes for html data frames. We could probably do something here with latex too.

**Comment by jkitchin** [comment]
With a sync you have to have a queue to make sure cell dependencies are correct. For example you don't want to run a cell that depends on the results from an earlier cell until the earlier cell is finished.

**Comment by gregsexton** [comment]
Oh, got it, concurrency is the concern. Under my current implementation, there isn't any explicit client-side causality - like you would get with a queue. Presumably you don't dequeue and submit the next request until you've received the result of the currently pending request? It's nice to make this explicit, I agree. Failure under this scenario is a bit trickier though. I guess you have some means of clearing out the queue and getting back to a good state?

The web server will have a queue though and it does seem to guarantee fairness here. i.e. executes in arrival order. ipython also seems to serialize the execution of entire requests, so you don't get interleaving of concurrently executing 'cells'. What I'm trying to say, is that happily this adds up to getting the ordering your looking for 'for free'. Having said that, it relies on http requests arriving in order - probably fine if you're running it locally, but I know some users spin up the driver remotely and all bets are off for requests arriving in order over the network.

Here's the dumb test I ran a bunch of times to quickly poke at this

    #+BEGIN_SRC ipython :session :exports both :results raw drawer :async t
    time.sleep(5)
    a = 1
    b = 7
    b
    #+END_SRC

    #+RESULTS:
    :RESULTS:
    7
    :END:

    #+BEGIN_SRC ipython :session :exports both :results raw drawer :async t
    time.sleep(3)
    b = 3
    b
    #+END_SRC

    #+RESULTS:
    :RESULTS:
    3
    :END:

    #+BEGIN_SRC ipython :session :exports both :results raw drawer :async t
    time.sleep(1)
    a + b
    #+END_SRC

    #+RESULTS:
    :RESULTS:
    4
    :END:

Off the back of this, I'm not keen to add complexity if it doesn't pay for itself. Do you use the queue for anything else?

Thanks for improving ob-ipython and making it more usable. Is there anything else we should look at merging upstream? I'm not yet familiar with all the improvements you've made. I guess for users of your library, it really doesn't matter which package features are in. Just wondering, for people that only need the ob-ipython component, if there's anything you've written you think could benefit them.

**Comment by jkitchin** [comment]
The way it works is when you run a cell it puts it on the queue. If no cell is running, that cell runs and removes itself from the queue. When a cell finishes running, it checks if there is another cell in the queue, and if so removes it and starts running, and that continues while there are cells in the queue. If there is an exception (I think) that the whole queue is cleared. It probably doesn't work perfectly though, because I also have nuke-ipython to restart it ;).

I guess I was not aware the web server itself has a queue. That is not obvious, but I guess it makes sense since the browser version must do something like this.

i am starting a sabbatical right now, and don't have a lot of time to devote to this beyond making it work for what I need right now. Hopefully that will change in the next few months, but it is hard to tell at the moment.

**Comment by jkitchin** [comment]
I have finally created a new branch using the new ob-ipython upstream repo: https://github.com/jkitchin/scimax/tree/ob-ipython-upstream

I still ended up monkey patching quite a few things to get it close to where I wanted. See the notes at https://github.com/jkitchin/scimax/blob/ob-ipython-upstream/scimax-ipython.org to see what is different.

It looks like it will be pretty awesome. After I work with the branch another week or so to make sure it all does what it should I will probably merge it into the master branch.

**Comment by jkitchin** [comment]
Closing this. commit f2726b6760dda899c75ceb76cf2dfe952adb6c88 should solve this.
