### ISSUE TITLE
rename of org-mime.el ?

### ISSUE THREAD

**Issue by csantosb** [jkitchin/scimax#160]
Hi,

First, thanks for this huge work, great package, really.

I just found there is another org-mime.el available on melpa [here](https://melpa.org/#/org-mime).

In order to have access to both, does it makes sense to rename this one to avoid
any namespace conflict ? Any other alternative you are aware of to avoid
conflicts ?

Thanks a lot,

**Comment by jkitchin** [comment]
They look like approximately the same files that originated from https://orgmode.org/worg/org-contrib/org-mime.html. The one in scimax is probably patched to fix some specific issue, and the one you refer to was put up a few months ago.

There will be unavoidable conflicts that changing the file name won't fix, since I guess the functions and variables are named the same. Whatever is loaded last will shadow earlier ones.

Do you use either of these? It is not loaded in scimax by default.

**Comment by jkitchin** [comment]
is there something in the scimax version you rely on? or does it get loaded because it comes first on your path? 

If you prefer the melpa one, probably you can load it with something like (load-file "path-to-what-you-want.el")

**Comment by jkitchin** [comment]
I have removed the old org-mime in scimax, and it is now loading the git repo for the one in MELPA. I have submitted a PR (https://github.com/org-mime/org-mime/pull/19) to fix equations and file attachments, which don't currently work.

Let me know if you find missing functionality from the old version.

**Comment by csantosb** [comment]
Great, thanks !
