### ISSUE TITLE
Using contacts.el effectively in scimax

### ISSUE THREAD

**Issue by shrysr** [jkitchin/scimax#208]
Using `mu cfind --format=org-contact`: I have my mu4e contacts in an org file in the org-contact format. 

How can I add the org file to the variable contacts-file?
I've tried the snippet below, but receive a stringp error. Therefore, there are no results from helm-contacts or ivy-contact or contacts-search. 
```
(add-to-list 'contacts-files
             '("~/my_org/my_contacts.org"))
```

What would be the best way to insert a contact into an org task? For example - is it possible to use something akin to a snippet which is an org link, and have it working with org-capture as well?

**Comment by jkitchin** [comment]
I think you should use: 

```
(add-to-list 'contacts-files
             "~/my_org/my_contacts.org")
```
I am not sure what you mean by insert a contact into an org task. You could certainly have a contact snippet. Probably there is a way to use capture too, but where would you capture them from?

**Comment by jkitchin** [comment]
It appears helm-contacts is not working as you describe. I guess something has changed on the helm side that I have not kept up with. I don't use this function these days.

You should not need any special config for ivy-contacts. How many contacts do you have? If it is a lot, then at least the first time it will be slow since it has to read all the files. After that, it saves these in a cache to speed things up, but every time you change a file it will reread them. I find many small files is better than one large file for performance. If performance is really slow, there is also a possibility to use org-db to access contacts too. I have about 6000 entries in mine. These do not include entries from mu4e, these are much faster to generate dynamically (which already happens in contacts.el). 

For capture, you can do something like this:

```
#+BEGIN_SRC emacs-lisp
(defun ivy-contacts-capture-email-template ()
  (let* ((contacts (ivy-contacts-candidates))
	 (contact (cdr (assoc (ivy-read "contact: " contacts) contacts)))
	 (name (cdr (assoc "NAME" contact)))
	 (email (cdr (assoc "EMAIL" contact)))
	 (subject (read-input "Subject: "))
	 (from-link (format "[[mu4e:query:from:%s]]"
			    (cdr (assoc "EMAIL" contact)))))
    (format "* TODO mail [[%s][%s]] about %s
Emails from: [[mu4e:query:from:%s]]
Mailto: [[mailto:%s?subject=%s]]"
	    (concat "contact:"
		    (cdr (assoc "NAME" contact)))
	    (cdr (assoc "NAME" contact))
	    subject
	    (cdr (assoc "EMAIL" contact))
	    (cdr (assoc "EMAIL" contact))
	    (org-link-escape subject))))


(add-to-list 'org-capture-templates
      '(("m" "Email" entry (file+headline "~/Dropbox/org-mode/email-tasks.org" "Tasks")
	 "%(ivy-contacts-capture-email-template)")))
#+END_SRC
```

**Comment by jkitchin** [comment]
I think I have fixed helm-contacts to work again. It is pretty slow though. I use ivy-contacts pretty regularly and find it ok.
