### ISSUE TITLE
Publishing a project to multiple formats, including ipynb

### ISSUE THREAD

**Issue by shrysr** [jkitchin/scimax#218]
I am customising my project publishing function as below. The HTML export works as expected. However, I am unable to use the ox-ipynb file export option to export a ipynb file. 

A normal export to ipynb works on this file using C-c e n n.  I would appreciate your advice to resolve this. 
```
(
 setq org-publish-project-alist
      '(
        ("html-static"
         :base-directory "./"
         :base-extension "org"
         :publishing-directory "./export/"
         :recursive t
         :publishing-function org-html-publish-to-html
         ;; :html-head "<link rel="stylesheet" href="http://dakrone.github.io/org2.css" type="text/css" />"
         )
        ("ipynb"
         :base-directory "./"
         :base-extension "org"
         :publishing-directory "./export/"
         :recursive t
         :publishing-function ox-ipynb-export-to-ipynb-file
         )

        ("org" 
         :components ("html-static" "ipynb" )
         )))
```

**Comment by jkitchin** [comment]
What is the problem that you see?

**Comment by jkitchin** [comment]
I guess the problem is that publishing requires an asynchronous export to work, and that is not currently possible with ox-ipynb. I am not sure how difficult it would be to make this work. ox-ipynb is not a typical exporter this way. You might be better off calling some kind of hook function that builds the ipynb files.
