### ISSUE TITLE
async pdf export + DocView

### ISSUE THREAD

**Issue by prtkm** [jkitchin/scimax#30]
Hi John,

I was wondering if you can suggest a way to do this. 

While writing a paper or a report, I would like to see a pdf on the side while I am typing, which automatically refreshes to sync with the changes I make in org-mode (perhaps in a periodic interval or every time I save the org file). I think this is pretty standard in something like overleaf or sharelatex, and it would add to the writing experience in scimax.

I know I can asynchronously export org to pdf like this ```(org-latex-export-to-pdf 't)``` and get the pdf open in a split buffer using DocView. To refresh the pdf, I tried auto-revert-mode on the DocView buffer, but it doesn't seem to work. It can't convert a half written pdf source to png and refuses to work once the final pdf file is written. The solution is to kill the buffer and reopen the pdf.

It seems like it should be possible to automate this whole process (and preferably to open the pdf on the last read page, and shrink/zoom it to fit the buffer), but I don't know enough elisp to do this very easily. Hopefully you can help ;)

**Comment by prtkm** [comment]
Maybe we can make a minor mode for this?

**Comment by jkitchin** [comment]
This works for me:

#+BEGIN_SRC emacs-lisp
(add-hook 'after-save-hook (lambda ()
			     (org-latex-export-to-pdf 't)
			     (find-file-other-window
			      (concat
			       (file-name-base (buffer-file-name))
			       ".pdf")))
	  nil t)
#+END_SRC

It is a buffer local hook that runs the async export every time you save
the buffer.

docview refreshes for me when the file rebuilds, and stays on the page
you were looking at. It is not fast, since it loads a whole new emacs. I
did not use autorevert mode.

A good pdf viewer would also refresh, although not many do that. Adobe,
for example does not, but Mac Preview does.

It seems like this could be a nice minor mode, I will play around with
it and see how it goes.

**Comment by prtkm** [comment]
I tried this, and you're right, docview isn't super convenient. I like the async + preview route better, that works pretty well with 2 screens.
