### ISSUE TITLE
Add different flyspell command to also store as autocorrect for spellings

### ISSUE THREAD

**Issue by JSpenced** [jkitchin/scimax#316]
I normally use the command `flyspell-auto-correct-previous-word` when I make a spelling error. But I guess because this cycles through entries maybe this doesn't get added to the abbrevs list? I just figured out about your abbrevs list for ispell now.

Also, is there a reason to use aspell over hunspell? I have seen people say for when they want to spellcheck camel case, but I am not sure which is better.

**Comment by jkitchin** [comment]
The `scimax-save-spellcheck-abbrev` var only works in the scimax version of `flyspell-correct-previous-word-generic`. You would have to similarly advise/monkeypatch  `flyspell-auto-correct-previous-word` to get the same behavior. You can see how it is done in scimax-autoformat-abbrev.el. I should probably modify this to be an :override advice so it is more obvious what is happening there. I will leave this open to remind me to do that.

I used to use hunspell, because it was a little more modern than aspell. However, I have found hunspell a challenge especially on windows, so I have recently switched back to aspell.

**Comment by JSpenced** [comment]
Okay, thanks. Neither seems to be updated in years, so probably not too much differences.

**Comment by jkitchin** [comment]
I don't notice much difference either. I am not sure what to expect on a spell-checker, but it is kind of disappointing to me there isn't more advancement or ways to update the dictionaries more frequently. I guess that would be pretty thankless work!
