### ISSUE TITLE
[Suggestion] Move mode dependant keymaps to make more modular?

### ISSUE THREAD

**Issue by SirSharpest** [jkitchin/scimax#329]
I use anaconda mode for my python editing, and I've ran into an issue where this reference to elpy was throwing my config. 

I wasn't sure if it's worth migrating to make it easier for non-elpy people to use your fantastic ob-ipy additions, or if I should just make a personal fork.

https://github.com/jkitchin/scimax/blob/85c4e302dfa55381f3418a0e134c693c8d59f7ff/scimax-ob.el#L320

**Comment by jkitchin** [comment]
I think the push above will address your problem in one of two ways. Maybe it will fix it just by pulling, because now if elpy-mode-mode is not defined, it will check if anaconda-mode-map is and use that instead. I am not sure this is totally going to work, if you have not loaded anaconda-mode already when this code runs though, and in that case, it will not use either map (which may be fine for you?).

Second, you can define scimax-src-block-keymaps in preload.el now, and then it will override the defcustom so you can make this variable be what ever you want.

**Comment by SirSharpest** [comment]
Great! Thanks!
