### ISSUE TITLE
Scimax Elfeed issue: changing the color of feeds

### ISSUE THREAD

**Issue by shrysr** [jkitchin/scimax#334]
scimax-elfeed.el has the following snippet for setting the background colors of certain feeds. However, since there is apparently no easy solution to syncing the database across computers, I run this elfeed on a terminal on my VPS. (This has actually worked rather well). Therefore on that machine over ssh - I have to discard the Leuven theme and etc for efficiency and cursor visibility. At the moment these feeds are completely invisible due to the limited terminal colors. 

I have tried defining the same snippet with "black", and killing all the elfeed buffers, however there has been no effect. I'm not sure why. Any advice would be appreciated. 

    (defface python-elfeed-entry
      '((t :background "Darkseagreen1"))
      "Marks a python Elfeed entry.")
    
    (defface emacs-elfeed-entry
      '((t :background "Lightblue1"))
      "Marks a python Elfeed entry.")
    
    (push '(python python-elfeed-entry)
          elfeed-search-face-alist)
    
    (push '(emacs emacs-elfeed-entry)
          elfeed-search-face-alist)

**Comment by jkitchin** [comment]
what if you set :background to nil? I guess another alternative might be to remove those entries from `elfeed-search-face-alist`, e.g.
```
(setq elfeed-search-face-alist (remove '(python python-elfeed-entry) elfeed-search-face-alist)
      elfeed-search-face-alist (remove '(emacs emacs-elfeed-entry) elfeed-search-face-alist))

```

**Comment by shrysr** [comment]
Thank you. i will have to check out applying nil instead of black. I've removed the entries for now, and that did work.

**Comment by uliw** [comment]
I added this to my user.el
```
(set-face-attribute 'python-elfeed-entry nil :background nil :weight 'normal)
(set-face-attribute 'emacs-elfeed-entry nil :background nil :weight 'normal)
(set-face-attribute 'elfeed-search-unread-title-face nil  :weight 'normal)
(set-face-attribute 'elfeed-search-feed-face nil :height '0.8)
```

**Comment by Arjay-El** [comment]
Sorry for being unclear. I was wondering whether Canvas X subscribers were going to be offered a discount as an incentive to buy Cadcomposer or will it be an add-on?

 

Thanks

**Comment by Arjay-El** [comment]
Please delete this sent to wrong address.Sent from the Galaxy
-------- Original message --------From: rjlilko@randing.ca Date: 2020-01-31  3:18 p.m.  (GMT-05:00) To: 'jkitchin/scimax' <reply@reply.github.com> Subject: RE: [jkitchin/scimax] Scimax Elfeed issue: changing the color of feeds (#334) Sorry for being unclear. I was wondering whether Canvas X subscribers were going to be offered a discount as an incentive to buy Cadcomposer or will it be an add-on? Thanks  From: Ulrich Wortmann <notifications@github.com> Sent: January 31, 2020 2:03 PMTo: jkitchin/scimax <scimax@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: Re: [jkitchin/scimax] Scimax Elfeed issue: changing the color of feeds (#334) I added this to my user.el(set-face-attribute 'python-elfeed-entry nil :background nil :weight 'normal)(set-face-attribute 'emacs-elfeed-entry nil :background nil :weight 'normal)(set-face-attribute 'elfeed-search-unread-title-face nil  :weight 'normal)(set-face-attribute 'elfeed-search-feed-face nil :height '0.8)—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
