### ISSUE TITLE
Which package is causing the autocorrection of capital letters?

### ISSUE THREAD

**Issue by Cumol** [jkitchin/scimax#343]
A tiny detail but an annoying one.

Something is stopping me from writing capital letters. For example, writing K**C**l in a normal org-mode buffer gets immediately turned into K**c**l. The "c" in KCl is supposed to be capital but is turned into lower case.
This is usually not so much of a issue, but gets annoying when you want to use the mchecm latex package where `$\ce{KCl)$ `yields the correct notation while `$\ce{Kcl}$ `does not.

**Comment by shrysr** [comment]
Afaik scimax-autoformat-mode (from the scimax-autoformat-abbrev package) is the only part of scimax that does an active change to text, and also has a hook connected to org-mode, but this has to be explicitly enabled first and is not on by default. If it is due to this mode - the changed text can be canceled with `C-q`. I've usually seen other packages like flyspell just underline but not directly make a direct change. You could check M-x scimax-toggle-abbrevs

**Comment by jkitchin** [comment]
This is from `dubcaps-mode`. You can turn it off with `M-x dubcaps-mode` I think.

**Comment by jkitchin** [comment]
This has also occasionally plagued me. I just added an ability to undo the change. dubcaps are more often a typo for me than a chemical formula, but  occasionally I do need dubcaps. This only corrects double caps, for three or more nothing is done.

**Comment by Cumol** [comment]
If I understand it correctly, the fix is that if you correct it right away, it keeps the correction.

If so, then it is working as intended. Thank you!

**Comment by jkitchin** [comment]
with the fix, if you type KC then l, then it "fixes" it to KCl, but right after that if you type C-/ (or whatever you use for undo) it will undo the "fix" to revert it back to KCl so you can have a double capital letter sequence.
