### ISSUE TITLE
Exporting to PDF via Beamer Class

### ISSUE THREAD

**Issue by mhlbapat** [jkitchin/scimax#390]
Hi!
I am trying to make presentations using the Beamer class. But when I try to export to pdf via latex using the key binding `C-e C-l l o`, it throws an error **Unknown LaTeX class ‘beamer’**. Although, when I make a TeX file using TeXLive, the beamer class is available.
I have to use _org-beamer-export-to-pdf_ to generate a pdf for the same. Is it possible to use the same key-bindings to generate a pdf for the beamer class?
Also, is there a way to include custom-defined **.sty** or **.cls** tex files in org-mode to produce a pdf using those templates?

**Comment by jkitchin** [comment]
The easiest way to include custom sty/cls files is to put them in the same directory as the org file. Otherwise you have to learn how to put them on the latex paths.

It is possible to use beamer with org (see https://orgmode.org/manual/Beamer-Export.html).  I don't have a lot of experience with it.

You need to load the ox-beamer library.

you can do this manually with 

`M-x ox-beamer`

or in your user.el file add

`(require 'ox-beamer)

**Comment by mhlbapat** [comment]
This works. Thanks a lot.
And yes. How different things have become in 2020!
