### ISSUE TITLE
Warning (initialization): Your ‘load-path’ seems to contain your ‘.emacs.d’ directory:

### ISSUE THREAD

**Issue by AKielhorn** [jkitchin/scimax#430]
Hello, it's me again.

I load scimax in the recommended way:

```
Emacs  -l ~/src/Emacs/scimax/init.el
```

But since 0322688 I get the following message:

```
Warning (initialization): Your ‘load-path’ seems to contain your ‘.emacs.d’ directory: 
/Users/axel/src/Emacs/scimax/user/
This is likely to cause problems...
Consider using a subdirectory instead, e.g.: /Users/axel/src/Emacs/scimax/user/lisp
```

Removing the ´\´ removes the error.

**Comment by jkitchin** [comment]
That is my fault, I added a / to the end of scimax-user-dir. The documentation says it should be there, and it wasn't, which was making some user files in another package get saved in the wrong place. 

The issue is related to putting that directory on the load path, which is convenient to do so you can load packages from your user dir. It is still added to the load path, but I wonder if it doesn't trigger that warning since it doesn't end with a /?

I also see that message too. I will go ahead and revert this

**Comment by AKielhorn** [comment]
I had this problem with `custom.el`.

It is read from `~/.emacs.d` but changes are written to `scimax/user`.

I solved it with a symlink.
