### ISSUE TITLE
Error trying jupyter-Julia and Git headache

### ISSUE THREAD

**Issue by Arjay-El** [jkitchin/scimax#471]
Question1:
I tried the jupyter-julia.org example and am told no org-babel function can be found. 'Julia' in the src line works by itself but if I use 'Jupyter-Julia' in the src line, I receive the error. Is there a specific org-babel execute file for  jupyter-Julia ?

Question2:
When scimax starts, I am now receiving this error. Doesn't really affect anything I am doing but I wondered if you had seen this or had any words of wisdom on its cause. I have git and its all fully pathed so its a mystery to me and google did not really help. The first line is a comment statement I put in to see where it started.

--> RUN Scimax init.el
'git' is not recognized as an internal or external command,
operable program or batch file.
Error: (file-missing "Searching for program" "No such file or directory" "git")

**Comment by jkitchin** [comment]
I also have been seeing the first problem recently. I don't know what happened, it used to work fine for me. It is the same issue for jupyter-R, but not mysteriously for python.

**Comment by jkitchin** [comment]
hm. ok, I got both of them to work again. For the issue was i am on a new machine, and the kernels were not installed. that led to the errors you found. try `jupyter-kernelspec list` in a shell to make sure the julia kernel is installed, and is the right name.

For your second error, this seems like the kind of error that happens when you launch emacs from an icon and not a shell. that usually means Emacs does not have the same path information as the shell, so it is missing info. it is weird if you put a full path there. I assume this happens in the line  (shell-command "git submodule update --init")?

**Comment by jkitchin** [comment]
you may want to install https://github.com/purcell/exec-path-from-shell.

the git submodule business will go away when I merge the homebrew branch in.
