### ISSUE TITLE
WIn11: WSL and Scimax 3 installation

### ISSUE THREAD

**Issue by Arjay-El** [jkitchin/scimax#477]
Have any WIn11 users figured out a step by step method on how to configure WSL2 to load a Scimax 3 config with a graphical interface? I have been stymied several times by WSL2 no being able to load all the ubuntu files required with various strange 'file not found' messages and 'no permission to access directory' messages. Not sure if Win11 security is interfering or whether it should all be on a D: drive to try to minimize security issues. If anyone has a method, could they please share it? Thanks! Feel free to PM me directly if you like.

**Comment by jkitchin** [comment]
I think any Emacs distro that is gui should work. It has been a long time since I had a windows machine to test on though, so I don't know. 

supposedly homebrew works on WSL2 now, and that might be a path to get a working installation. I documented what I think could work at https://github.com/jkitchin/scimax#homebrew.
