### ISSUE TITLE
json-readtable-error

### ISSUE THREAD

**Issue by broncodev** [jkitchin/scimax#76]
Hi! Thank you very much for org-ref. I am a new user, and I think that it will make my life much easier.
I am trying to add a PDF to a new .bib file by dragging it (I don't know if I can post it here: http://biomechanical.asmedigitalcollection.asme.org/article.aspx?articleid=1427237 ), but I get `json-readtable-error` . I can add the reference if I type the title.

org-ref: Version 1.0.0 (git-commit eab60109956b00868d60f0738acb0cf70fef15c0)
GNU Emacs 24.4.1 (x86_64-pc-linux-gnu, GTK+ Version 3.4.2) of 2015-01-11 on maritornes, modified by Debian

Thanks!

**Comment by jkitchin** [comment]
json-readtable-errors are usually from errors at dx.doi.org. Usually you are better off using doi-add-bibtex-entry and a DOI than dragging a pdf onto a bib file. Dragging a pdf can be unreliable since org-ref has to try to find a doi in it, and there can be more than one in the pdf, or errors in what it finds.

**Comment by broncodev** [comment]
Thank you very much!
